import { db, kd_dominoTable } from '../../../database/database'
import { CellType } from '../types'

type BulkInsertKDDomino = {
  value: number
  left_cell_type: CellType
  left_cell_crowns: number
  right_cell_type: CellType
  right_cell_crowns: number
}

const dominos: BulkInsertKDDomino[] = [
  {
    value: 1,
    left_cell_type: CellType.wheat,
    left_cell_crowns: 0,
    right_cell_type: CellType.wheat,
    right_cell_crowns: 0,
  },
  {
    value: 2,
    left_cell_type: CellType.wheat,
    left_cell_crowns: 0,
    right_cell_type: CellType.wheat,
    right_cell_crowns: 0,
  },
  {
    value: 3,
    left_cell_type: CellType.forest,
    left_cell_crowns: 0,
    right_cell_type: CellType.forest,
    right_cell_crowns: 0,
  },
  {
    value: 4,
    left_cell_type: CellType.forest,
    left_cell_crowns: 0,
    right_cell_type: CellType.forest,
    right_cell_crowns: 0,
  },
  {
    value: 5,
    left_cell_type: CellType.forest,
    left_cell_crowns: 0,
    right_cell_type: CellType.forest,
    right_cell_crowns: 0,
  },
  {
    value: 6,
    left_cell_type: CellType.forest,
    left_cell_crowns: 0,
    right_cell_type: CellType.forest,
    right_cell_crowns: 0,
  },
  {
    value: 7,
    left_cell_type: CellType.lake,
    left_cell_crowns: 0,
    right_cell_type: CellType.lake,
    right_cell_crowns: 0,
  },
  {
    value: 8,
    left_cell_type: CellType.lake,
    left_cell_crowns: 0,
    right_cell_type: CellType.lake,
    right_cell_crowns: 0,
  },
  {
    value: 9,
    left_cell_type: CellType.lake,
    left_cell_crowns: 0,
    right_cell_type: CellType.lake,
    right_cell_crowns: 0,
  },
  {
    value: 10,
    left_cell_type: CellType.land,
    left_cell_crowns: 0,
    right_cell_type: CellType.land,
    right_cell_crowns: 0,
  },
  {
    value: 11,
    left_cell_type: CellType.land,
    left_cell_crowns: 0,
    right_cell_type: CellType.land,
    right_cell_crowns: 0,
  },
  {
    value: 12,
    left_cell_type: CellType.swamp,
    left_cell_crowns: 0,
    right_cell_type: CellType.swamp,
    right_cell_crowns: 0,
  },
  {
    value: 13,
    left_cell_type: CellType.wheat,
    left_cell_crowns: 0,
    right_cell_type: CellType.forest,
    right_cell_crowns: 0,
  },
  {
    value: 14,
    left_cell_type: CellType.wheat,
    left_cell_crowns: 0,
    right_cell_type: CellType.lake,
    right_cell_crowns: 0,
  },
  {
    value: 15,
    left_cell_type: CellType.wheat,
    left_cell_crowns: 0,
    right_cell_type: CellType.land,
    right_cell_crowns: 0,
  },
  {
    value: 16,
    left_cell_type: CellType.wheat,
    left_cell_crowns: 0,
    right_cell_type: CellType.swamp,
    right_cell_crowns: 0,
  },
  {
    value: 17,
    left_cell_type: CellType.forest,
    left_cell_crowns: 0,
    right_cell_type: CellType.lake,
    right_cell_crowns: 0,
  },
  {
    value: 18,
    left_cell_type: CellType.forest,
    left_cell_crowns: 0,
    right_cell_type: CellType.land,
    right_cell_crowns: 0,
  },
  {
    value: 19,
    left_cell_type: CellType.wheat,
    left_cell_crowns: 1,
    right_cell_type: CellType.forest,
    right_cell_crowns: 0,
  },
  {
    value: 20,
    left_cell_type: CellType.wheat,
    left_cell_crowns: 1,
    right_cell_type: CellType.lake,
    right_cell_crowns: 0,
  },
  {
    value: 21,
    left_cell_type: CellType.wheat,
    left_cell_crowns: 1,
    right_cell_type: CellType.land,
    right_cell_crowns: 0,
  },
  {
    value: 22,
    left_cell_type: CellType.wheat,
    left_cell_crowns: 1,
    right_cell_type: CellType.swamp,
    right_cell_crowns: 0,
  },
  {
    value: 23,
    left_cell_type: CellType.wheat,
    left_cell_crowns: 1,
    right_cell_type: CellType.mine,
    right_cell_crowns: 0,
  },
  {
    value: 24,
    left_cell_type: CellType.forest,
    left_cell_crowns: 1,
    right_cell_type: CellType.wheat,
    right_cell_crowns: 0,
  },
  {
    value: 25,
    left_cell_type: CellType.forest,
    left_cell_crowns: 1,
    right_cell_type: CellType.wheat,
    right_cell_crowns: 0,
  },
  {
    value: 26,
    left_cell_type: CellType.forest,
    left_cell_crowns: 1,
    right_cell_type: CellType.wheat,
    right_cell_crowns: 0,
  },
  {
    value: 27,
    left_cell_type: CellType.forest,
    left_cell_crowns: 1,
    right_cell_type: CellType.wheat,
    right_cell_crowns: 0,
  },
  {
    value: 28,
    left_cell_type: CellType.forest,
    left_cell_crowns: 1,
    right_cell_type: CellType.lake,
    right_cell_crowns: 0,
  },
  {
    value: 29,
    left_cell_type: CellType.forest,
    left_cell_crowns: 1,
    right_cell_type: CellType.land,
    right_cell_crowns: 0,
  },
  {
    value: 30,
    left_cell_type: CellType.lake,
    left_cell_crowns: 1,
    right_cell_type: CellType.wheat,
    right_cell_crowns: 0,
  },
  {
    value: 31,
    left_cell_type: CellType.lake,
    left_cell_crowns: 1,
    right_cell_type: CellType.wheat,
    right_cell_crowns: 0,
  },
  {
    value: 32,
    left_cell_type: CellType.lake,
    left_cell_crowns: 1,
    right_cell_type: CellType.forest,
    right_cell_crowns: 0,
  },
  {
    value: 33,
    left_cell_type: CellType.lake,
    left_cell_crowns: 1,
    right_cell_type: CellType.forest,
    right_cell_crowns: 0,
  },
  {
    value: 34,
    left_cell_type: CellType.lake,
    left_cell_crowns: 1,
    right_cell_type: CellType.forest,
    right_cell_crowns: 0,
  },
  {
    value: 35,
    left_cell_type: CellType.lake,
    left_cell_crowns: 1,
    right_cell_type: CellType.forest,
    right_cell_crowns: 0,
  },
  {
    value: 36,
    left_cell_type: CellType.wheat,
    left_cell_crowns: 0,
    right_cell_type: CellType.land,
    right_cell_crowns: 1,
  },
  {
    value: 37,
    left_cell_type: CellType.lake,
    left_cell_crowns: 0,
    right_cell_type: CellType.land,
    right_cell_crowns: 1,
  },
  {
    value: 38,
    left_cell_type: CellType.wheat,
    left_cell_crowns: 0,
    right_cell_type: CellType.swamp,
    right_cell_crowns: 1,
  },
  {
    value: 39,
    left_cell_type: CellType.land,
    left_cell_crowns: 0,
    right_cell_type: CellType.swamp,
    right_cell_crowns: 1,
  },
  {
    value: 40,
    left_cell_type: CellType.mine,
    left_cell_crowns: 1,
    right_cell_type: CellType.wheat,
    right_cell_crowns: 0,
  },
  {
    value: 41,
    left_cell_type: CellType.wheat,
    left_cell_crowns: 0,
    right_cell_type: CellType.land,
    right_cell_crowns: 2,
  },
  {
    value: 42,
    left_cell_type: CellType.lake,
    left_cell_crowns: 0,
    right_cell_type: CellType.land,
    right_cell_crowns: 2,
  },
  {
    value: 43,
    left_cell_type: CellType.wheat,
    left_cell_crowns: 0,
    right_cell_type: CellType.swamp,
    right_cell_crowns: 2,
  },
  {
    value: 44,
    left_cell_type: CellType.land,
    left_cell_crowns: 0,
    right_cell_type: CellType.swamp,
    right_cell_crowns: 2,
  },
  {
    value: 45,
    left_cell_type: CellType.mine,
    left_cell_crowns: 2,
    right_cell_type: CellType.wheat,
    right_cell_crowns: 0,
  },
  {
    value: 46,
    left_cell_type: CellType.swamp,
    left_cell_crowns: 0,
    right_cell_type: CellType.mine,
    right_cell_crowns: 2,
  },
  {
    value: 47,
    left_cell_type: CellType.swamp,
    left_cell_crowns: 0,
    right_cell_type: CellType.mine,
    right_cell_crowns: 2,
  },
  {
    value: 48,
    left_cell_type: CellType.wheat,
    left_cell_crowns: 0,
    right_cell_type: CellType.mine,
    right_cell_crowns: 3,
  },
]

export const insertDominos = async () => {
  await kd_dominoTable(db).bulkInsert({
    columnsToInsert: ['value', 'left_cell_type', 'left_cell_crowns', 'right_cell_type', 'right_cell_crowns'],
    records: dominos,
  })
}
